### ISSUE TITLE
【天天优惠大乐透】cookie过期，死循环报错

### ISSUE THREAD

**Issue by Tenkai17** [wuzhi01/MyActions#19]
❗️天天优惠大乐透, 错误!
TypeError: Cannot read property 'prizeName' of undefined
at $.post (/home/runner/scripts/jd_daydlt.js:108:49)
at got.post.then.t (/home/runner/scripts/jd_daydlt.js:261:5677)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by wuzhi01** [comment]
我目前的仓库里面并没有jd_daydlt这个脚本你是如何运行并且报错的
