### ISSUE TITLE
京喜农场出了问题

### ISSUE THREAD

**Issue by fy592621372** [wuzhi01/MyActions#26]
可能是京东官方把京喜农场更新了，目前京喜农场的脚本一直报错。

**Comment by Tenkai17** [comment]
TypeError: Cannot read property '1' of null
    at $.(anonymous function) (/home/runner/scripts/jd_jxnc.js:53:50204)
    at isSurge.isLoon.isQuanX.isNode.got.on.then.t (/home/runner/scripts/jd_jxnc.js:57:4860)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by wuzhi01** [comment]
同步作者新脚本了
