### ISSUE TITLE
喜马拉雅运行错误

### ISSUE THREAD

**Issue by cisco6005** [wuzhi01/MyActions#6]
新手任务】

【阅读】

【bubble】
Traceback (most recent call last):
  File "xmly_speed.py", line 1072, in <module>
    run()
  File "xmly_speed.py", line 1025, in run
    bubble(cookies)  # 收金币气泡
  File "xmly_speed.py", line 559, in bubble
    if not result["data"]["effectiveBubbles"]:
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.

**Comment by wuzhi01** [comment]
测试无异常，建议自查
