### ISSUE TITLE
京喜工厂打工助力失败，提示京东服务器访问数据为空

### ISSUE THREAD

**Issue by anakinlee99** [wuzhi01/MyActions#7]
京喜工厂打工助力失败，提示京东服务器访问数据为空，手动运行也提示同样错误。
请大佬帮忙看一下是什么原因，能不能修复。
具体log如下：

----------------------------------------------------------------------------------------------------------------------------------------------
随机取20个码放到您固定的互助码后面(不影响已有固定互助)
第1个京东账号将要助力的好友["EBKF96NEIjafPXEj156fVA==","4J64q0wPBO9KYK3SrFOu9Q==","M7RAgr_EtABMv4X65FO4ig==","l8FBpP0JzbRcQ9YFGlMWLw==","UgNa-yLQ0ZPgb7QF35Jd7Q==","2H-B47rXNcc3feIDmmOgqQ==","-almUOGjFVDIS47gA-CrtA==","nqbup-w9gHbxTVZdN4ohzQ==","6FcOVZY-58qrM5YCFivpDw==","VWbN6Y-xUktvAqT3E9Zn3w==","T022v_13RxwZ91ffPR_wlPcNfACjVWnYaS5kRrbA","T0205KkcH1lQpB6qW3uX06FuCjVWnYaS5kRrbA","T0225KkcRR1K8wXXJxKiwaIIdACjVWnYaS5kRrbA","T018v_h6QBsa9VfeKByb1ACjVWnYaS5kRrbA","T016aGPImbWDIsNs9Zd1CjVWnYaS5kRrbA","T020anX1lb-5IPJt9JJyQH-MCjVWnYaS5kRrbA","T0225KkcRBoRp1SEJBP1nKIDdgCjVWnYaS5kRrbA","T023aEXSlrKgIvNiIRj3kPIMc44CjVWnYaS5kRrbA"]
不能为自己助力,跳过
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at safeGet (/jd/scripts/jd_dreamFactory.js:1369:21)
    at /jd/scripts/jd_dreamFactory.js:424:15
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_dreamFactory.js:1541:4774)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
京东服务器访问数据为空，请检查自身设备网络情况
助力朋友[4J64q0wPBO9KYK3SrFOu9Q==]失败：undefined
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at safeGet (/jd/scripts/jd_dreamFactory.js:1369:21)
    at /jd/scripts/jd_dreamFactory.js:424:15
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_dreamFactory.js:1541:4774)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
京东服务器访问数据为空，请检查自身设备网络情况
助力朋友[M7RAgr_EtABMv4X65FO4ig==]失败：undefined
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at safeGet (/jd/scripts/jd_dreamFactory.js:1369:21)
    at /jd/scripts/jd_dreamFactory.js:424:15
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_dreamFactory.js:1541:4774)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
京东服务器访问数据为空，请检查自身设备网络情况
助力朋友[l8FBpP0JzbRcQ9YFGlMWLw==]失败：undefined
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at safeGet (/jd/scripts/jd_dreamFactory.js:1369:21)
    at /jd/scripts/jd_dreamFactory.js:424:15
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_dreamFactory.js:1541:4774)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
京东服务器访问数据为空，请检查自身设备网络情况

**Comment by anakinlee99** [comment]
更新了之后已经解决了，感谢大佬
